---
- hosts: localhost
  connection: local
  vars:
    dcos_cluster: <Insert your DCOS Master URL here>
    app_grp: dev
    seal_id: 102188-jpgbds
    tensorflow_cluster_identifier: tf-cluster1
    package: tensorflow
    job_name: mnist
    
  tasks:
  - name: Do a DCOS config show 
    command: dcos config show

  - name: Do a DCOS Enterprise CLI setup 
    command: dcos package install dcos-enterprise-cli --yes

  - name: Create a private and public keypair for the service, in this case {{ app_grp }}_{{ seal_id }}
    command: dcos security org service-accounts keypair {{ tensorflow_cluster_identifier }}-private.pem {{ tensorflow_cluster_identifier }}-public.pem

  - name: Create a new service account using the previously created key
    command: dcos security org service-accounts create -p {{ tensorflow_cluster_identifier }}-public.pem -d "For {{ tensorflow_cluster_identifier }} service account" {{ app_grp }}_{{ package }}

  - name: Create a secret to hold the private key for strict
    command: dcos security secrets create-sa-secret --strict {{ tensorflow_cluster_identifier }}-private.pem {{ app_grp }}_{{ package }} {{ app_grp }}/{{ seal_id }}/{{ tensorflow_cluster_identifier }}/{{ package }}-secret

# Permissions
  - name: Grant user nobody user to create
    command: dcos security org users grant {{ app_grp }}_{{ package }} dcos:mesos:master:task:user:nobody create 

  - name: Grant Permission to create tasks in that namespace
    command: dcos security org users grant {{ app_grp }}_{{ package }} dcos:mesos:master:task:app_id:/{{ app_grp }}/{{ seal_id }}/{{ tensorflow_cluster_identifier }} create

  - name: Allow dev_tensorflow to register with Mesos and consume resources from the dev-tensorflow role
    command: dcos security org users grant {{ app_grp }}_{{ package }}  dcos:mesos:master:framework:role:{{ app_grp }}__{{ seal_id }}__{{ tensorflow_cluster_identifier }}__{{ job_name }}-role create

  - name: Allow {{ app_grp }}__{{ seal_id }}__{{ tensorflow_cluster_identifier }}__{{ job_name }}-role to reserve resources
    command: dcos security org users grant {{ app_grp }}_{{ package }} dcos:mesos:master:reservation:role:{{ app_grp }}__{{ seal_id }}__{{ tensorflow_cluster_identifier }}__{{job_name }}-role create 

  - name: Allow {{ app_grp }}_{{ package }} principal to reserve resources
    command: dcos security org users grant {{ app_grp }}_{{ package }} dcos:mesos:master:reservation:principal:{{ app_grp }}_{{ package }}  create

  - name: Allow {{ app_grp }}_{{ package }} principal to delete resources
    command: dcos security org users grant {{ app_grp }}_{{ package }} dcos:mesos:master:reservation:principal:{{ app_grp }}_{{ package }} delete

  - name: Allow {{ app_grp }}__{{ seal_id }}__{{ tensorflow_cluster_identifier }}__{{ job_name }}-role to access volumes
    command: dcos security org users grant {{ app_grp }}_{{ package }} dcos:mesos:master:volume:role:{{ app_grp }}__{{ seal_id }}__{{ tensorflow_cluster_identifier }}__{{ job_name }}-role create

  - name: Allow {{ app_grp }}_{{ package }}  principal to access volumes
    command: dcos security org users grant {{ app_grp }}_{{ package }} dcos:mesos:master:volume:principal:{{ app_grp }}_{{ package }} create

  - name: Allow {{ app_grp }}_{{ package }}  principal to delete volumes
    command: dcos security org users grant {{ app_grp }}_{{ package }} dcos:mesos:master:volume:principal:{{ app_grp }}_{{ package }} delete

  - name: Create your options.json 
    template: 
      src: ../templates/options_tf.j2
      dest: ../output/options_tf.json 
  
  - name: Deploy TF Package
    command: dcos package install beta-tensorflow --options=../output/options_tf.json --yes


